modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="examlpe_mod"
version="1.0.0"
displayName="examlpe_mod++"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="simongurin, MCreator"

[[dependencies.examlpe_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




